set.seed("991155")
edf_norm = ecdf(rnorm(150))
pdf("normalcdfplot.pdf",width=6,height=5)
par(mfrow=c(1,1))
plot(edf_norm, verticals = TRUE, do.p = FALSE, main = "EDF and CDF")
tt = seq(from = -3, to = 3, by = 0.01)
lines(tt, pnorm(tt), lty = 2, lwd = 2, col = "red")
legend(1.5, 0.2, c("EDF", "CDF"), lty = c(1,2), lwd = c(1.5,2), col=c("black", "red"))
graphics.off()
